apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-microservice
  template:
    metadata:
      labels:
        app: my-microservice
    spec:
      containers:
        - name: my-microservice
          image: aadityakulk/calc-microservice
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://aaditya:calc123@mongo-service:27017
