apiVersion: v1
kind: Service
metadata:
  name: my-microservice-service
spec:
  selector:
    app: my-microservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
